FROM fedora:41

RUN dnf install -y \
    git \
    neovim \
    python3 \
    vim-enhanced \
    zsh \
    && dnf clean all

RUN useradd -m -s /bin/bash testuser

USER testuser
WORKDIR /home/testuser

CMD ["/bin/bash"]
